In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[0]

1

In [6]:
a[2]

3

In [7]:
a[1]

2

In [8]:
b = [4,5,6]

In [9]:
b_array = np.array(b)

In [10]:
b_array

array([4, 5, 6])

In [11]:
b_array[0]

4

In [12]:
b_array[1]

5

In [13]:
b_array[2]

6

In [14]:
c = (1,2,3,4)

In [15]:
c_array = np.array(c)

In [16]:
type(c_array)

numpy.ndarray

In [17]:
shape(c_array)

NameError: name 'shape' is not defined

In [18]:
c_array.shape()

TypeError: 'tuple' object is not callable

In [19]:
import time

In [20]:
import sys

In [21]:
time_now = time.time()

In [22]:
print(time_now)

1666005839.3740711

In [23]:
time.ctime(time_now)

'Mon Oct 17 16:53:59 2022'

In [24]:
b = range(1000)

In [25]:
b

range(0, 1000)

In [30]:
c = np.array(b)

In [31]:
c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

to get the size of each integer

In [36]:
print(sys.getsizeof(5))

28

In [37]:
len(b)

1000

In [38]:
print(sys.getsizeof(50))

28

so total size of b array which is formed by using range function of python is?

In [39]:
print(sys.getsizeof(5)*len(b))

28000

Creating the same array using numpy

In [40]:
numpy_array = np.arange(1000)

In [41]:
len(numpy_array)

1000

In [46]:
print(numpy_array.size*numpy_array.itemsize)

8000

In [47]:
print(numpy_array.itemsize)

8

so each item of the numpy array is of size 8 while size of the each list item was 28,

so clearly we can say numpy uses less memory. So there is a significant difference in memory.

2. Let's look at the speed of numpy:

In [51]:
A = np.arange(1000)

In [52]:
B = np.arange(1000)

In [66]:
start_time = time.time()
result1 = A+B                 
end_time = time.time()
print("Execution time is: ", (end_time - start_time)*1000 )

Execution time is:  0.2658367156982422

In [63]:
result1

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  300,  302,  304,  306,
        308,  310,  312,  314,  316,  318,  320,  322,  324,  326,  328,
        330,  332,  334,  336,  338,  340,  342,  344,  346,  348,  350,
        352,  354,  356,  358,  360,  362,  364,  366,  368,  370,  372,
        374,  376,  378,  380,  382,  384,  386,  388,  390,  392,  394,
        396,  398,  400,  402,  404,  406,  408,  410,  412,  414,  416,
        418,  420,  422,  424,  426,  428,  430,  432,  434,  436,  438,
        440,  442,  444,  446,  448,  450,  452,  454,  456,  458,  460,
        462,  464,  466,  468,  470,  472,  474,  476,  478,  480,  482,
        484,  486,  488,  490,  492,  494,  496,  498,  500,  502,  504,
        506,  508,  510,  512,  514,  516,  518,  520,  522,  524,  526,
        528,  530,  532,  534,  536,  538,  540,  542,  544,  546,  548,
        550,  552,  554,  556,  558,  560,  562,  564,  566,  568,  570,
        572,  574,  576,  578,  580,  582,  584,  586,  588,  590,  592,
        594,  596,  598,  600,  602,  604,  606,  608,  610,  612,  614,
        616,  618,  620,  622,  624,  626,  628,  630,  632,  634,  636,
        638,  640,  642,  644,  646,  648,  650,  652,  654,  656,  658,
        660,  662,  664,  666,  668,  670,  672,  674,  676,  678,  680,
        682,  684,  686,  688,  690,  692,  694,  696,  698,  700,  702,
        704,  706,  708,  710,  712,  714,  716,  718,  720,  722,  724,
        726,  728,  730,  732,  734,  736,  738,  740,  742,  744,  746,
        748,  750,  752,  754,  756,  758,  760,  762,  764,  766,  768,
        770,  772,  774,  776,  778,  780,  782,  784,  786,  788,  790,
        792,  794,  796,  798,  800,  802,  804,  806,  808,  810,  812,
        814,  816,  818,  820,  822,  824,  826,  828,  830,  832,  834,
        836,  838,  840,  842,  844,  846,  848,  850,  852,  854,  856,
        858,  860,  862,  864,  866,  868,  870,  872,  874,  876,  878,
        880,  882,  884,  886,  888,  890,  892,  894,  896,  898,  900,
        902,  904,  906,  908,  910,  912,  914,  916,  918,  920,  922,
        924,  926,  928,  930,  932,  934,  936,  938,  940,  942,  944,
        946,  948,  950,  952,  954,  956,  958,  960,  962,  964,  966,
        968,  970,  972,  974,  976,  978,  980,  982,  984,  986,  988,
        990,  992,  994,  996,  998, 1000, 1002, 1004, 1006, 1008, 1010,
       1012, 1014, 1016, 1018, 1020, 1022, 1024, 1026, 1028, 1030, 1032,
       1034, 1036, 1038, 1040, 1042, 1044, 1046, 1048, 1050, 1052, 1054,
       1056, 1058, 1060, 1062, 1064, 1066, 1068, 1070, 1072, 1074, 1076,
       1078, 1080, 1082, 1084, 1086, 1088, 1090, 1092, 1094, 1096, 1098,
       1100, 1102, 1104, 1106, 1108, 1110, 1112, 1114, 1116, 1118, 1120,
       1122, 1124, 1126, 1128, 1130, 1132, 1134, 1136, 1138, 1140, 1142,
       1144, 1146, 1148, 1150, 1152, 1154, 1156, 1158, 1160, 1162, 1164,
       1166, 1168, 1170, 1172, 1174, 1176, 1178, 1180, 1182, 1184, 1186,
       1188, 1190, 1192, 1194, 1196, 1198, 1200, 1202, 1204, 1206, 1208,
       1210, 1212, 1214, 1216, 1218, 1220, 1222, 1224, 1226, 1228, 1230,
       1232, 1234, 1236, 1238, 1240, 1242, 1244, 1246, 1248, 1250, 1252,
       1254, 1256, 1258, 1260, 1262, 1264, 1266, 1268, 1270, 1272, 1274,
       1276, 1278, 1280, 1282, 1284, 1286, 1288, 1290, 1292, 1294, 1296,
       1298, 1300, 1302, 1304, 1306, 1308, 1310, 1312, 1314, 1316, 1318,
       1320, 1322, 1324, 1326, 1328, 1330, 1332, 1334, 1336, 1338, 1340,
       1342, 1344, 1346, 1348, 1350, 1352, 1354, 1356, 1358, 1360, 1362,
       1364, 1366, 1368, 1370, 1372, 1374, 1376, 1378, 1380, 1382, 1384,
       1386, 1388, 1390, 1392, 1394, 1396, 1398, 1400, 1402, 1404, 1406,
       1408, 1410, 1412, 1414, 1416, 1418, 1420, 1422, 1424, 1426, 1428,
       1430, 1432, 1434, 1436, 1438, 1440, 1442, 1444, 1446, 1448, 1450,
       1452, 1454, 1456, 1458, 1460, 1462, 1464, 1466, 1468, 1470, 1472,
       1474, 1476, 1478, 1480, 1482, 1484, 1486, 1488, 1490, 1492, 1494,
       1496, 1498, 1500, 1502, 1504, 1506, 1508, 1510, 1512, 1514, 1516,
       1518, 1520, 1522, 1524, 1526, 1528, 1530, 1532, 1534, 1536, 1538,
       1540, 1542, 1544, 1546, 1548, 1550, 1552, 1554, 1556, 1558, 1560,
       1562, 1564, 1566, 1568, 1570, 1572, 1574, 1576, 1578, 1580, 1582,
       1584, 1586, 1588, 1590, 1592, 1594, 1596, 1598, 1600, 1602, 1604,
       1606, 1608, 1610, 1612, 1614, 1616, 1618, 1620, 1622, 1624, 1626,
       1628, 1630, 1632, 1634, 1636, 1638, 1640, 1642, 1644, 1646, 1648,
       1650, 1652, 1654, 1656, 1658, 1660, 1662, 1664, 1666, 1668, 1670,
       1672, 1674, 1676, 1678, 1680, 1682, 1684, 1686, 1688, 1690, 1692,
       1694, 1696, 1698, 1700, 1702, 1704, 1706, 1708, 1710, 1712, 1714,
       1716, 1718, 1720, 1722, 1724, 1726, 1728, 1730, 1732, 1734, 1736,
       1738, 1740, 1742, 1744, 1746, 1748, 1750, 1752, 1754, 1756, 1758,
       1760, 1762, 1764, 1766, 1768, 1770, 1772, 1774, 1776, 1778, 1780,
       1782, 1784, 1786, 1788, 1790, 1792, 1794, 1796, 1798, 1800, 1802,
       1804, 1806, 1808, 1810, 1812, 1814, 1816, 1818, 1820, 1822, 1824,
       1826, 1828, 1830, 1832, 1834, 1836, 1838, 1840, 1842, 1844, 1846,
       1848, 1850, 1852, 1854, 1856, 1858, 1860, 1862, 1864, 1866, 1868,
       1870, 1872, 1874, 1876, 1878, 1880, 1882, 1884, 1886, 1888, 1890,
       1892, 1894, 1896, 1898, 1900, 1902, 1904, 1906, 1908, 1910, 1912,
       1914, 1916, 1918, 1920, 1922, 1924, 1926, 1928, 1930, 1932, 1934,
       1936, 1938, 1940, 1942, 1944, 1946, 1948, 1950, 1952, 1954, 1956,
       1958, 1960, 1962, 1964, 1966, 1968, 1970, 1972, 1974, 1976, 1978,
       1980, 1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998])

In [58]:
A1 = range(1000)
B1 = range(1000)

In [64]:
start_time = time.time()
result2 = [(x+y) for x,y in zip(A1,B1)]
end_time = time.time()
print("Execution time is: ", (end_time - start_time)*1000 )

Execution time is:  1.0058879852294922

so we can see execution time of numpy array to do the same stuff is around 25 percent

In [67]:
A

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [68]:
A.size

1000

In [69]:
A.itemsize

8

In [70]:
a = np.array([[1,2], [3,4], [5,6]])

In [71]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
a[0][1]

2

In [73]:
a[2][1]

6

In [74]:
a[2][0]

5

Finding the dimensions of the numpy array

In [75]:
a.ndim

2

In [76]:
a.size

6

In [77]:
a = np.array([[1,2], [3,4], [5,6] , [7,8] ])

In [78]:
a.size

8

In [79]:
a.itemsize

8

In [80]:
a.shape

(4, 2)

In [81]:
a = np.array([[1,2], [3,4], [5,6]])

In [83]:
a.shape

(3, 2)

We can set the data type of the items by using dtype =

In [84]:
a = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)

In [85]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [86]:
a.itemsize

8

In [91]:
a = np.array([[1,2], [3,4], [5,6]], dtype = np.complex_)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

Creating arrays of zeros and ones, 

Very useful when we are building some neural networks and we need to give some initialisations,

we can use the starting points as zeros or ones as shown:

In [92]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [93]:
b = np.ones((4,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
len(b)

4

Size give the total number of elements in the numpy array

In [95]:
b.size

20

In [96]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
print(np.char.add(["abc","123"],["def", "456"]))

['abcdef' '123456']

In [98]:
print(np.char.multiply("Hello ", 3))

Hello Hello Hello

In [102]:
print(np.char.center("Hello", 20,fillchar = "-"))

-------Hello--------

Other text based operations uing numpy

In [103]:
print(np.char.capitalize("hello world"))

Hello world

In [104]:
print(np.char.title("hello world"))

Hello World

In [105]:
print(np.char.lower("HELLO world"))

hello world

In [107]:
print(np.char.upper("hello world"))

HELLO WORLD

Splitting by space

In [108]:
print(np.char.split("Python is fun and easy"))

['Python', 'is', 'fun', 'and', 'easy']

Splitting by lines

In [109]:
print(np.char.splitlines("Hello First line \nNext line"))

['Hello First line ', 'Next line']

In [112]:
print(np.char.strip("      Removes leading and trailing spaces    "))

Removes leading and trailing spaces

In [117]:
print(np.char.strip("aaaaaRemoves leading and trailing a'saaaaa",'a'))

Removes leading and trailing a's

In [116]:
print(np.char.join("-","hihihaha"))

h-i-h-i-h-a-h-a

useful when we are processing dates data

In [118]:
print(np.char.join([":","-"],["ymd","dmy"]))

['y:m:d' 'd-m-y']

In [123]:
print(np.char.replace("He is a good dancer", "is" ,"was"))

He was a good dancer

In [124]:
print(np.char.replace("20 04 1995", " ",":"))

20:04:1995

In [125]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a = ["this" , "is" , "a" , "string" , "array"]

In [128]:
a_numpy_array = np.array(a)

In [129]:
a_numpy_array

array(['this', 'is', 'a', 'string', 'array'], dtype='<U6')

In [130]:
a_numpy_array.ndim

1

In [131]:
a_numpy_array.size

5

In [133]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [135]:
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])